# Generated by Django 4.2.5 on 2023-12-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
