# Generated by Django 4.2.5 on 2023-12-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_animal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='in_work',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
